// Initial kana sets organized by difficulty level
export const KANA_SETS = {
  1: [
    { hiragana: 'あ', romaji: 'a' },
    { hiragana: 'い', romaji: 'i' },
    { hiragana: 'う', romaji: 'u' },
    { hiragana: 'え', romaji: 'e' },
    { hiragana: 'お', romaji: 'o' },
  ],
  2: [
    { hiragana: 'か', romaji: 'ka' },
    { hiragana: 'き', romaji: 'ki' },
    { hiragana: 'く', romaji: 'ku' },
    { hiragana: 'け', romaji: 'ke' },
    { hiragana: 'こ', romaji: 'ko' },
  ],
  3: [
    { hiragana: 'さ', romaji: 'sa' },
    { hiragana: 'し', romaji: 'shi' },
    { hiragana: 'す', romaji: 'su' },
    { hiragana: 'せ', romaji: 'se' },
    { hiragana: 'そ', romaji: 'so' },
  ],
  4: [
    { hiragana: 'た', romaji: 'ta' },
    { hiragana: 'ち', romaji: 'chi' },
    { hiragana: 'つ', romaji: 'tsu' },
    { hiragana: 'て', romaji: 'te' },
    { hiragana: 'と', romaji: 'to' },
  ],
  5: [
    { hiragana: 'な', romaji: 'na' },
    { hiragana: 'に', romaji: 'ni' },
    { hiragana: 'ぬ', romaji: 'nu' },
    { hiragana: 'ね', romaji: 'ne' },
    { hiragana: 'の', romaji: 'no' },
  ],
  6: [
    { hiragana: 'は', romaji: 'ha' },
    { hiragana: 'ひ', romaji: 'hi' },
    { hiragana: 'ふ', romaji: 'fu' },
    { hiragana: 'へ', romaji: 'he' },
    { hiragana: 'ほ', romaji: 'ho' },
  ],
  7: [
    { hiragana: 'ま', romaji: 'ma' },
    { hiragana: 'み', romaji: 'mi' },
    { hiragana: 'む', romaji: 'mu' },
    { hiragana: 'め', romaji: 'me' },
    { hiragana: 'も', romaji: 'mo' },
  ],
  8: [
    { hiragana: 'や', romaji: 'ya' },
    { hiragana: 'ゆ', romaji: 'yu' },
    { hiragana: 'よ', romaji: 'yo' },
  ],
  9: [
    { hiragana: 'ら', romaji: 'ra' },
    { hiragana: 'り', romaji: 'ri' },
    { hiragana: 'る', romaji: 'ru' },
    { hiragana: 'れ', romaji: 're' },
    { hiragana: 'ろ', romaji: 'ro' },
  ],
  10: [
    { hiragana: 'わ', romaji: 'wa' },
    { hiragana: 'を', romaji: 'wo' },
    { hiragana: 'ん', romaji: 'n' },
  ],
  11: [
    { hiragana: 'が', romaji: 'ga' },
    { hiragana: 'ぎ', romaji: 'gi' },
    { hiragana: 'ぐ', romaji: 'gu' },
    { hiragana: 'げ', romaji: 'ge' },
    { hiragana: 'ご', romaji: 'go' },
  ],
  12: [
    { hiragana: 'ざ', romaji: 'za' },
    { hiragana: 'じ', romaji: 'ji' },
    { hiragana: 'ず', romaji: 'zu' },
    { hiragana: 'ぜ', romaji: 'ze' },
    { hiragana: 'ぞ', romaji: 'zo' },
  ],
  13: [
    { hiragana: 'だ', romaji: 'da' },
    { hiragana: 'ぢ', romaji: 'ji' },
    { hiragana: 'づ', romaji: 'zu' },
    { hiragana: 'で', romaji: 'de' },
    { hiragana: 'ど', romaji: 'do' },
  ],
  14: [
    { hiragana: 'ば', romaji: 'ba' },
    { hiragana: 'び', romaji: 'bi' },
    { hiragana: 'ぶ', romaji: 'bu' },
    { hiragana: 'べ', romaji: 'be' },
    { hiragana: 'ぼ', romaji: 'bo' },
  ],
  15: [
    { hiragana: 'ぱ', romaji: 'pa' },
    { hiragana: 'ぴ', romaji: 'pi' },
    { hiragana: 'ぷ', romaji: 'pu' },
    { hiragana: 'ぺ', romaji: 'pe' },
    { hiragana: 'ぽ', romaji: 'po' },
  ],
};
